import sharp from 'sharp';
import { writeFileSync } from 'fs';
import { resolve, dirname, basename } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const rawArgs = process.argv.slice(2);
const flags = new Set<string>();
const keyValues: Record<string, string> = {};
const positional: string[] = [];

for (let i = 0; i < rawArgs.length; i++) {
  if (rawArgs[i] === '--output' && i + 1 < rawArgs.length) {
    keyValues.output = rawArgs[++i];
  } else if (rawArgs[i].startsWith('--')) {
    flags.add(rawArgs[i]);
  } else {
    positional.push(rawArgs[i]);
  }
}

const inputFile = positional[0] ?? 'globe.png';
const grayscale = flags.has('--grayscale');
const alpha = flags.has('--alpha');
const invert = flags.has('--invert');

function pixelLandness(r: number, g: number, b: number, a: number): number {
  if (a < 80) return 0;
  if (b > r + 18 && b > g + 6 && b > 110) return 0;
  const minRGB = Math.min(r, g, b);
  if (minRGB >= 230) return 0;
  if (minRGB <= 80) return 255;
  return ((230 - minRGB) * 255 / (230 - 80)) | 0;
}

function pixelBrightness(r: number, g: number, b: number, a: number): number {
  if (a < 80) return 0;
  return (0.299 * r + 0.587 * g + 0.114 * b) | 0;
}

function boxBlur3x3(src: Uint8Array, w: number, h: number): Uint8Array {
  const tmp = new Uint8Array(w * h);
  for (let y = 0; y < h; y++) {
    const off = y * w;
    for (let x = 0; x < w; x++) {
      const xL = x > 0 ? x - 1 : x;
      const xR = x < w - 1 ? x + 1 : x;
      tmp[off + x] = ((src[off + xL] + src[off + x] + src[off + xR]) / 3) | 0;
    }
  }
  const dst = new Uint8Array(w * h);
  for (let y = 0; y < h; y++) {
    const yU = (y > 0 ? y - 1 : y) * w;
    const yC = y * w;
    const yD = (y < h - 1 ? y + 1 : y) * w;
    for (let x = 0; x < w; x++) {
      dst[yC + x] = ((tmp[yU + x] + tmp[yC + x] + tmp[yD + x]) / 3) | 0;
    }
  }
  return dst;
}

async function main() {
  const imagePath = resolve(ROOT, inputFile);
  const mode = alpha ? 'alpha' : grayscale ? 'grayscale' : 'earth';
  console.log(`Processing: ${inputFile} (${mode} mode)${invert ? ' (inverted)' : ''}`);
  const image = sharp(imagePath);
  const metadata = await image.metadata();
  const w = metadata.width!;
  const h = metadata.height!;

  const { data } = await image.ensureAlpha().raw().toBuffer({ resolveWithObject: true });

  const pixels = w * h;
  let mask = new Uint8Array(pixels);
  const classify = alpha ? (_r: number, _g: number, _b: number, a: number) => a
    : grayscale ? pixelBrightness : pixelLandness;
  for (let i = 0; i < pixels; i++) {
    const p = i * 4;
    mask[i] = classify(data[p], data[p + 1], data[p + 2], data[p + 3]);
  }

  if (invert) {
    for (let i = 0; i < pixels; i++) {
      mask[i] = 255 - mask[i];
    }
  }

  for (let pass = 0; pass < 2; pass++) {
    mask = boxBlur3x3(mask, w, h);
  }

  const packedLen = Math.ceil(pixels / 2);
  const bin = new Uint8Array(4 + packedLen);
  bin[0] = (w >> 8) & 0xFF;
  bin[1] = w & 0xFF;
  bin[2] = (h >> 8) & 0xFF;
  bin[3] = h & 0xFF;

  for (let i = 0; i < pixels; i += 2) {
    const hi = Math.min(15, (mask[i] / 17 + 0.5) | 0);
    const lo = i + 1 < pixels ? Math.min(15, (mask[i + 1] / 17 + 0.5) | 0) : 0;
    bin[4 + (i >> 1)] = (hi << 4) | lo;
  }

  const b64 = Buffer.from(bin).toString('base64');

  const name = basename(inputFile, '.png');
  const outputPath = keyValues.output
    ? resolve(keyValues.output)
    : resolve(ROOT, 'src', 'maps', `${name}.ts`);

  const dataTs = `// Auto-generated by scripts/extract-texture.ts — do not edit
const data: string = '${b64}';
export default data;
`;

  writeFileSync(outputPath, dataTs);
  console.log(`${outputPath} generated`);
}

main().catch(console.error);
