import sharp from 'sharp';
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

function pixelLandness(r: number, g: number, b: number, a: number): number {
  if (a < 80) return 0;
  if (b > r + 18 && b > g + 6 && b > 110) return 0;
  const minRGB = Math.min(r, g, b);
  if (minRGB >= 230) return 0;
  if (minRGB <= 80) return 255;
  return ((230 - minRGB) * 255 / (230 - 80)) | 0;
}

function boxBlur3x3(src: Uint8Array, w: number, h: number): Uint8Array {
  const tmp = new Uint8Array(w * h);
  for (let y = 0; y < h; y++) {
    const off = y * w;
    for (let x = 0; x < w; x++) {
      const xL = x > 0 ? x - 1 : x;
      const xR = x < w - 1 ? x + 1 : x;
      tmp[off + x] = ((src[off + xL] + src[off + x] + src[off + xR]) / 3) | 0;
    }
  }
  const dst = new Uint8Array(w * h);
  for (let y = 0; y < h; y++) {
    const yU = (y > 0 ? y - 1 : y) * w;
    const yC = y * w;
    const yD = (y < h - 1 ? y + 1 : y) * w;
    for (let x = 0; x < w; x++) {
      dst[yC + x] = ((tmp[yU + x] + tmp[yC + x] + tmp[yD + x]) / 3) | 0;
    }
  }
  return dst;
}

async function main() {
  const image = sharp(resolve(ROOT, 'globe.png'));
  const metadata = await image.metadata();
  const w = metadata.width!;
  const h = metadata.height!;

  const { data } = await image.ensureAlpha().raw().toBuffer({ resolveWithObject: true });

  const pixels = w * h;
  let mask = new Uint8Array(pixels);
  for (let i = 0; i < pixels; i++) {
    const p = i * 4;
    mask[i] = pixelLandness(data[p], data[p + 1], data[p + 2], data[p + 3]);
  }

  for (let pass = 0; pass < 2; pass++) {
    mask = boxBlur3x3(mask, w, h);
  }

  // Quantize to 4 bits (16 levels) and pack two values per byte
  const packedLen = Math.ceil(pixels / 2);
  const bin = new Uint8Array(4 + packedLen);
  bin[0] = (w >> 8) & 0xFF;
  bin[1] = w & 0xFF;
  bin[2] = (h >> 8) & 0xFF;
  bin[3] = h & 0xFF;

  for (let i = 0; i < pixels; i += 2) {
    const hi = Math.min(15, (mask[i] / 17 + 0.5) | 0);
    const lo = i + 1 < pixels ? Math.min(15, (mask[i + 1] / 17 + 0.5) | 0) : 0;
    bin[4 + (i >> 1)] = (hi << 4) | lo;
  }

  writeFileSync(resolve(ROOT, 'globe.bin'), bin);
  console.log(`globe.bin: ${bin.length} bytes (${w}x${h}, ${pixels} pixels)`);

  // Generate embedded data module
  const b64 = Buffer.from(bin).toString('base64');

  const dataTs = `// Auto-generated by scripts/extract-texture.ts — do not edit
const DATA = '${b64}';

const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const LUT = new Uint8Array(128);
for (let i = 0; i < 64; i++) LUT[B64.charCodeAt(i)] = i;

function decodeBase64(s: string): Uint8Array {
  const len = s.length;
  let pad = 0;
  if (s[len - 1] === '=') pad++;
  if (s[len - 2] === '=') pad++;
  const bytes = new Uint8Array((len * 3 >> 2) - pad);
  let j = 0;
  for (let i = 0; i < len; i += 4) {
    const a = LUT[s.charCodeAt(i)];
    const b = LUT[s.charCodeAt(i + 1)];
    const c = LUT[s.charCodeAt(i + 2)];
    const d = LUT[s.charCodeAt(i + 3)];
    bytes[j++] = (a << 2) | (b >> 4);
    if (j < bytes.length) bytes[j++] = ((b & 0xF) << 4) | (c >> 2);
    if (j < bytes.length) bytes[j++] = ((c & 3) << 6) | d;
  }
  return bytes;
}

let _decoded: { width: number; height: number; mask: Uint8Array } | null = null;

export function getTextureData(): { width: number; height: number; mask: Uint8Array } {
  if (_decoded) return _decoded;
  const bin = decodeBase64(DATA);
  const width = (bin[0] << 8) | bin[1];
  const height = (bin[2] << 8) | bin[3];
  const pixels = width * height;
  const mask = new Uint8Array(pixels);
  for (let i = 0; i < pixels; i++) {
    const nibble = (i & 1) ? (bin[4 + (i >> 1)] & 0x0F) : (bin[4 + (i >> 1)] >> 4);
    mask[i] = nibble * 17;
  }
  _decoded = { width, height, mask };
  return _decoded;
}
`;

  writeFileSync(resolve(ROOT, 'src', 'data.ts'), dataTs);
  console.log('src/data.ts generated');
}

main().catch(console.error);
